export const adminModules = {
  products: {
    label: "Products",
    endpoint: "products",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "brand_name", label: "Brand" },
      { key: "category_name", label: "Category" },
      { key: "is_featured", label: "Featured", type: "boolean" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "brand", label: "Brand", type: "select", source: "brands", optionLabel: "name", required: true },
      { name: "category", label: "Category", type: "select", source: "categories", optionLabel: "name", required: true },
      { name: "name", label: "Product Name", required: true },
      { name: "model", label: "Model", required: true },
      { name: "product_type", label: "Product Type" },
      { name: "paper_size", label: "Paper Size" },
      { name: "print_speed", label: "Print Speed" },
      { name: "print_resolution", label: "Print Resolution" },
      { name: "memory", label: "Memory" },
      { name: "tray_capacity", label: "Tray Capacity" },
      { name: "connectivity", label: "Connectivity" },
      { name: "warranty", label: "Warranty" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "key_features", label: "Key Features", type: "textarea" },
      { name: "specifications", label: "Specifications", type: "textarea" },
      { name: "brochure_file", label: "Brochure", type: "file", accept: ".pdf,.doc,.docx" },
      { name: "image", label: "Image", type: "file", accept: "image/*" },
      { name: "images", label: "Product Gallery Images", type: "file", accept: "image/*", multiple: true, existingKey: "images" },
      { name: "is_featured", label: "Featured", type: "checkbox", defaultValue: false },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  brands: {
    label: "Brands",
    endpoint: "brands",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "description", label: "Description" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Brand Name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "logo", label: "Logo", type: "file", accept: "image/*" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  categories: {
    label: "Categories",
    endpoint: "categories",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "brand_name", label: "Brand" },
      { key: "slug", label: "Slug" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "brand", label: "Brand", type: "select", source: "brands", optionLabel: "name" },
      { name: "name", label: "Category Name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image", label: "Image", type: "file", accept: "image/*" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  locations: {
    label: "Locations",
    endpoint: "locations",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "city", label: "City" },
      { key: "area", label: "Area" },
      { key: "phone", label: "Phone" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Branch / Dealer Name", required: true },
      { name: "city", label: "City", required: true },
      { name: "area", label: "Area" },
      { name: "address", label: "Full Address", type: "textarea", required: true },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "working_hours", label: "Working Hours" },
      { name: "google_maps_url", label: "Google Maps URL", type: "url" },
      { name: "latitude", label: "Latitude", type: "number", step: "any", min: -90, max: 90 },
      { name: "longitude", label: "Longitude", type: "number", step: "any", min: -180, max: 180 },
      { name: "services_available", label: "Services Available", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
};

export const adminNav = [
  { label: "Dashboard", path: "/admin-panel/dashboard" },
  { label: "Products", path: "/admin-panel/products" },
  { label: "Brands", path: "/admin-panel/brands" },
  { label: "Categories", path: "/admin-panel/categories" },
  { label: "Locations", path: "/admin-panel/locations" },
];
