# Generated by Django 5.2.15 on 2026-06-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('features', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('sales', models.BooleanField(default=True)),
                ('rental', models.BooleanField(default=False)),
                ('amc', models.BooleanField(default=False)),
                ('service_support', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
    ]
