# Generated by Django 5.2.15 on 2026-06-19 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'area', 'name']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='location',
            name='map_url',
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='services_available',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='working_hours',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
