# Generated by Django 5.2.15 on 2026-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
