export const adminModules = {
  locations: {
    label: "Locations",
    endpoint: "locations",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "city", label: "City" },
      { key: "phone", label: "Phone" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Location Name", required: true },
      { name: "city", label: "City", required: true },
      { name: "address", label: "Address", type: "textarea", required: true },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email", type: "email" },
      { name: "map_url", label: "Map URL", type: "url" },
      { name: "display_order", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  brands: {
    label: "Brands",
    endpoint: "brands",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "name", label: "Brand Name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "logo", label: "Logo", type: "file", accept: "image/*", requiredOnCreate: true },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  categories: {
    label: "Categories",
    endpoint: "categories",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "brand_name", label: "Brand" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "brand", label: "Brand", type: "select", source: "brands", optionLabel: "name", required: true },
      { name: "name", label: "Category Name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image", label: "Image", type: "file", accept: "image/*" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  products: {
    label: "Products",
    endpoint: "products",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "category_name", label: "Category" },
      { key: "featured", label: "Featured", type: "boolean" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "category", label: "Category", type: "select", source: "categories", optionLabel: "name", required: true },
      { name: "name", label: "Product Name", required: true },
      { name: "model_number", label: "Model Number" },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "image", label: "Image", type: "file", accept: "image/*", requiredOnCreate: true },
      { name: "features", label: "Features", type: "textarea" },
      { name: "specifications", label: "Specifications", type: "textarea" },
      { name: "brochure", label: "Brochure", type: "file", accept: ".pdf,.doc,.docx" },
      { name: "sales", label: "Sales", type: "checkbox", defaultValue: true },
      { name: "rental", label: "Rental", type: "checkbox", defaultValue: false },
      { name: "amc", label: "AMC", type: "checkbox", defaultValue: false },
      { name: "service_support", label: "Service Support", type: "checkbox", defaultValue: true },
      { name: "featured", label: "Featured", type: "checkbox", defaultValue: false },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  enquiries: {
    label: "Enquiries",
    endpoint: "enquiries",
    titleField: "name",
    columns: [
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "phone", label: "Phone", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "location", label: "Location", required: true },
      { name: "machine_requirement", label: "Machine Requirement", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { value: "new", label: "New" },
          { value: "contacted", label: "Contacted" },
          { value: "closed", label: "Closed" },
        ],
        defaultValue: "new",
      },
    ],
  },
  testimonials: {
    label: "Testimonials",
    endpoint: "testimonials",
    titleField: "customer_name",
    columns: [
      { key: "customer_name", label: "Customer" },
      { key: "company_name", label: "Company" },
      { key: "rating", label: "Rating" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "customer_name", label: "Customer Name", required: true },
      { name: "company_name", label: "Company Name" },
      { name: "logo", label: "Logo", type: "file", accept: "image/*" },
      { name: "review", label: "Review", type: "textarea", required: true },
      { name: "rating", label: "Rating", type: "number", min: 1, max: 5, defaultValue: 5, required: true },
      { name: "relationship_duration", label: "Relationship Duration" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
};

export const adminNav = [
  { label: "Dashboard", path: "/admin-panel" },
  ...Object.keys(adminModules).map((key) => ({
    label: adminModules[key].label,
    path: `/admin-panel/${key}`,
  })),
];