from pathlib import Path
from shutil import copyfile

from django.conf import settings
from django.core.management.base import BaseCommand
from django.utils.text import slugify

from brands.models import Brand
from categories.models import Category
from products.models import Product

CONTACT = "Contact for details"
FRONTEND_BROCHURES = settings.BASE_DIR.parent.parent / "frontend" / "public" / "brochures"


def specs(**values):
    return {key: value for key, value in values.items() if value and value != CONTACT}


CATALOG = [
    {
        "brand": "RISO",
        "model": "ComColor FT1430",
        "category": "High-Speed Monochrome Inkjet Printer",
        "product_type": "Production Printer",
        "paper_size": "A3; standard tray 90 x 148 mm to 340 x 550 mm, feed tray 182 x 182 mm to 297 x 432 mm",
        "print_speed": "140 ppm A4 LEF simplex; 70 sheets/min duplex",
        "print_resolution": "600 x 600 dpi",
        "memory": "4 GB",
        "tray_capacity": "Standard tray height up to 110 mm; feed tray height up to 56 mm (2 trays); output tray height up to 56 mm",
        "connectivity": "Ethernet 1000BASE-T/100BASE-TX/10BASE-T; TCP/IP, HTTP/HTTPS, DHCP, FTP, LPR, IPP, SNMP, Port 9100, IPv4/IPv6, IPSec",
        "warranty": CONTACT,
        "description": "The RISO ComColor FT1430 is a high-speed monochrome inkjet printer for demanding print rooms that need fast A3 output, low heat generation and efficient bulk document production.",
        "key_features": [
            "Ultra high-speed 140 ppm monochrome inkjet printing",
            "First print time of 5 seconds or less for A4 long-edge feed",
            "Line-type inkjet system with oil-based pigment black ink",
            "600 x 600 dpi print and data processing resolution",
            "Optional finishing for stapling, punching, folding, stacking and booklet making",
            "Low power consumption noted as 520 W with ComColor FT1430 without folder unit",
        ],
        "specifications": specs(
            **{
                "Print Method": "Line-type inkjet system",
                "Ink Type": "Oil-based pigment ink (Black)",
                "First Print Time": "5 sec. or less (A4 long-edge feed)",
                "Continuous Print Speed": "A4 LEF 140 ppm simplex / 70 sheets per minute duplex; A4 108 ppm simplex; B4 90 ppm simplex; A3 79 ppm simplex",
                "Paper Weight": "Standard tray 46 to 210 gsm; feed tray 52 to 104 gsm",
                "Printable Area": "Maximum 310 x 544 mm",
                "Page Description Language": "RISORINC/C IV",
                "Supported OS": "Microsoft Windows / Windows Server; optional macOS; Linux compatible with PPD only",
                "Network Interface": "Ethernet 1000BASE-T/100BASE-TX/10BASE-T, 2 channel",
                "Storage Capacity": "500 GB hard disk, approx. 430 GB available",
                "Power Source": "AC 100-240 V, 10.0-5.0 A, 50-60 Hz",
                "Power Consumption": "Max. 1,000 W; ready 80 W or less; sleep 2 W or less; stand-by 0.4 W or less",
                "Operating Noise": "65 dB(A) or less at printing",
                "Dimensions": "In use: 1,030 x 735 x 1,115 mm; cover/tray closed: 775 x 710 x 970 mm",
                "Weight": "Approx. 132 kg",
                "Optional Accessories": "Scanner HS7000, Additional 2000 Sheet Feeder FG20, Face Down Finisher F10, Multifunction Finisher FG20/Folder Unit FG20, stacking trays, ComColorExpress RS1200C, PS Kit FG10 and card/envelope feed kits",
            }
        ),
        "brochure": "riso-comcolor-ft1430.pdf",
        "is_featured": True,
    },
    {
        "brand": "RISO",
        "model": "CV1200",
        "category": "Digital Duplicators",
        "product_type": "Digital Duplicator",
        "paper_size": "100 x 148 mm to 297 x 420 mm",
        "print_speed": "60, 80 and 100 ppm",
        "print_resolution": "300 x 300 dpi",
        "memory": CONTACT,
        "tray_capacity": "Approx. 1000-sheet paper supply; approx. 800-sheet paper receiving",
        "connectivity": "USB PC Interface",
        "warranty": CONTACT,
        "description": "The RISO CV1200 is a compact digital duplicator option for cost-conscious customers who need dependable high-volume duplication with RISO support.",
        "key_features": [
            "High-speed digital master-making with fully automatic printing",
            "Three print speed levels: 60, 80 and 100 ppm",
            "Approx. 1000-sheet paper supply and approx. 800-sheet receiving capacity",
            "300 x 300 dpi scanning and printing resolution",
            "USB PC interface for computer connection",
        ],
        "specifications": specs(
            **{
                "Master Making / Printing Methods": "High-speed digital master-making / fully automatic printing",
                "Original Type": "Sheet",
                "Original Size": "90 x 140 mm to 310 x 435 mm",
                "Original Paper Weight": "50 to 107 gsm",
                "Original Paper Capacity": "1 sheet",
                "Scanning Area": "Maximum 297 x 435 mm",
                "Printing Paper Weight": "35 to 128 gsm",
                "Image Processing Mode": "Line, Photo, Duo, Pencil",
                "Master-making Time": "Approx. 39 seconds or less for B4 originals",
                "Printing Area": "251 x 357 mm",
                "Ink Supply": "Fully automatic, 800 ml per cartridge",
                "Master Supply/Disposal": "Fully automatic; B4 approx. 200 sheets per roll; disposal capacity approx. 30 sheets",
                "User Interface": "LED panel",
                "Optional Accessories": "Not Available",
                "Operating Noise": "Max. 69 dB(A) at 100 sheets per minute",
                "Power Source": "AC 100-120 V / 220-240 V, 50-60 Hz",
                "Power Consumption": "Max. 160 W; ready 15 W or lower; sleep 10 W or lower; power-off 0.5 W or lower",
                "Functions": "Original scanning mode, scanning level, enlargement/reduction, 2-Up, speed, print position, program, confidential, meter display, proof, direct printing, auto sleep, auto power-off, RISO iQuality System",
                "Dimensions": "In use: 1280 x 655 x 515 mm; storage: 665 x 655 x 505 mm",
                "Required Space": "1280 x 1255 x 845 mm",
                "Weight": "Approx. 64 kg",
            }
        ),
        "brochure": "riso-cv1200.pdf",
    },
    {
        "brand": "RISO",
        "model": "CV3230",
        "category": "Digital Duplicators",
        "product_type": "B4 Digital Duplicator",
        "paper_size": "100 x 148 mm to 297 x 420 mm",
        "print_speed": "60 to 130 sheets per minute (five steps variable)",
        "print_resolution": "300 x 600 dpi",
        "memory": CONTACT,
        "tray_capacity": "Approx. 1000-sheet paper supply; approx. 800-sheet paper receiving",
        "connectivity": "Direct USB flash drive printing; USB PC Interface",
        "warranty": CONTACT,
        "description": "The RISO CV3230 combines cost-saving digital duplication with a compact B4 design, simple controls and practical USB workflow support.",
        "key_features": [
            "High-speed printing up to 130 ppm",
            "High-quality 300 x 600 dpi output",
            "128 x 64 dot easy-to-use LCD panel",
            "Direct USB flash drive printing",
            "Inbuilt USB PC interface",
            "Approx. 10-sheet auto document feeder",
        ],
        "specifications": specs(
            **{
                "Master Making / Printing Methods": "High-speed digital master-making / fully automatic printing",
                "Original Type": "Sheet",
                "Original Size": "90 x 140 mm to 310 x 435 mm",
                "Original Paper Weight": "50 to 107 gsm",
                "Original Paper Capacity": "Approx. 10 sheets",
                "Scanning Area": "Maximum 297 x 435 mm",
                "Printing Paper Weight": "50 to 157 gsm",
                "Image Processing Mode": "Line, Photo, Duo, Pencil",
                "Scanning Resolution": "300 x 600 dpi",
                "Printing Image Resolution": "300 x 600 dpi",
                "Master-making Time": "Approx. 35 seconds or less for B4 originals",
                "Printing Area": "251 x 357 mm",
                "Ink Supply": "Fully automatic, 800 ml per cartridge",
                "Master Supply/Disposal": "Fully automatic, 200 sheets per roll; disposal capacity approx. 30 sheets",
                "User Interface": "LCD panel",
                "Optional Accessories": "Color Drum (Cylinder), Job Separator",
                "Operating Noise": "Max. 68 dB(A) at 100 sheets per minute",
                "Power Source": "AC 100-120 V / 220-240 V, 50-60 Hz",
                "Power Consumption": "Max. 200 W; ready 15 W or less; sleep 10 W or less",
                "Functions": "Line/Photo/Duo/Pencil, enlargement/reduction, 2-Up, auto process, program, confidential, direct printing, USB flash-via-printing, energy saving mode, RISO i Quality System",
                "Dimensions": "In use: 1280 x 655 x 515 mm; storage: 665 x 655 x 505 mm",
                "Required Space": "1280 x 1255 x 845 mm",
                "Weight": "Approx. 65 kg",
            }
        ),
        "brochure": "riso-cv3230.pdf",
        "is_featured": True,
    },
    {
        "brand": "RISO",
        "model": "SF5330",
        "category": "Digital Duplicators",
        "product_type": "Digital Duplicator",
        "paper_size": CONTACT,
        "print_speed": CONTACT,
        "print_resolution": CONTACT,
        "memory": CONTACT,
        "tray_capacity": CONTACT,
        "connectivity": CONTACT,
        "warranty": CONTACT,
        "description": "The RISO SF5330 is positioned for customers who need efficient, dependable digital duplication with RISO's production-focused workflow.",
        "key_features": [
            "RISO SF series digital duplicator for high-volume duplication",
            "Suitable for education, institutions and commercial print rooms",
            "Brochure text extraction did not expose reliable specifications; consult Surya Enterprises for confirmed configuration",
        ],
        "specifications": {},
        "brochure": "riso-sf5330.pdf",
    },
]

CATALOG.extend([
    {
        "brand": "Xerox / Fujifilm",
        "model": "B230",
        "category": "A4 Mono Printers",
        "product_type": "A4 Mono Printer",
        "paper_size": "A4",
        "print_speed": "36 ppm",
        "print_resolution": CONTACT,
        "memory": "256 MB",
        "tray_capacity": "250-sheet tray; 1-sheet manual feed",
        "connectivity": "Network, Wi-Fi, Direct Print",
        "warranty": "1 year",
        "description": "Compact A4 mono printer for everyday office document printing.",
        "key_features": ["A4 mono printer", "36 ppm print speed", "Two-sided printing", "Network, Wi-Fi and Direct Print support"],
        "specifications": specs(Processor="1.0 GHz", Duplex="Two-sided printing", **{"Manual Feed": "1 sheet"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B310",
        "category": "A4 Mono Printers",
        "product_type": "A4 Mono Printer",
        "paper_size": "A4",
        "print_speed": "42 ppm",
        "print_resolution": CONTACT,
        "memory": "256 MB",
        "tray_capacity": "250-sheet main tray; 100-sheet bypass",
        "connectivity": "Network, Wi-Fi, Direct Print",
        "warranty": "1 year",
        "description": "A4 mono printer option for offices that need reliable black-and-white output.",
        "key_features": ["A4 mono printer", "42 ppm print speed", "Two-sided printing", "Network, Wi-Fi and Direct Print support"],
        "specifications": specs(Processor="1.05 GHz", Duplex="Two-sided printing", **{"Bypass Tray": "100 sheets"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B410",
        "category": "A4 Mono Printers",
        "product_type": "A4 Mono Printer",
        "paper_size": "A4",
        "print_speed": "50 ppm",
        "print_resolution": CONTACT,
        "memory": "1000 MB",
        "tray_capacity": "550-sheet tray; 100-sheet manual feed",
        "connectivity": "Network, Wi-Fi, Direct Printing",
        "warranty": "1 year",
        "description": "Business-focused A4 mono printer for daily office printing requirements.",
        "key_features": ["A4 mono printer", "50 ppm print speed", "Two-sided printing", "1000 MB print memory"],
        "specifications": specs(Processor="1.0 GHz", Duplex="Two-sided printing", **{"Manual Feed": "100 sheets"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B225",
        "category": "A4 Mono MFP",
        "product_type": "A4 Mono Multifunction Printer",
        "paper_size": "A4",
        "print_speed": "36 ppm",
        "print_resolution": CONTACT,
        "memory": "512 MB",
        "tray_capacity": "250-sheet main tray; 1-sheet manual feed; 50-sheet ADF",
        "connectivity": "Network, Wi-Fi",
        "warranty": "1 year",
        "description": "Compact A4 mono multifunction printer for small office print, copy and scan workflows.",
        "key_features": ["Copy, print and scan", "36 ppm speed", "Two-sided printing", "50-sheet ADF"],
        "specifications": specs(Processor="1.0 GHz", Functions="Copy / Print / Scan", ADF="50 sheets", Duplex="Two-sided printing"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B305",
        "category": "A4 Mono MFP",
        "product_type": "A4 Mono Multifunction Printer",
        "paper_size": "A4",
        "print_speed": "40 ppm",
        "print_resolution": CONTACT,
        "memory": "512 MB",
        "tray_capacity": "250-sheet tray; 100-sheet manual feed; 50-sheet ADF",
        "connectivity": "Network, Wi-Fi, Direct Print",
        "warranty": "1 year",
        "description": "A4 mono MFP for teams that need dependable multifunction document handling.",
        "key_features": ["Copy, print and scan", "40 ppm speed", "Two-sided printing", "Network, Wi-Fi and Direct Print support"],
        "specifications": specs(Processor="1.0 GHz", Functions="Copy / Print / Scan", ADF="50 sheets", Duplex="Two-sided printing"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B315",
        "category": "A4 Mono MFP",
        "product_type": "A4 Mono Multifunction Printer",
        "paper_size": "A4",
        "print_speed": "42 ppm",
        "print_resolution": CONTACT,
        "memory": "512 MB",
        "tray_capacity": "250-sheet main tray; 100-sheet manual feed; 50-sheet ADF",
        "connectivity": "Network, Wi-Fi",
        "warranty": "1 year",
        "description": "Business A4 mono MFP for offices looking for one machine to handle daily document workflows.",
        "key_features": ["Copy, print and scan", "42 ppm speed", "Two-sided printing", "50-sheet ADF"],
        "specifications": specs(Processor="1.0 GHz", Functions="Copy / Print / Scan", ADF="50 sheets", Duplex="Two-sided printing"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Fujifilm",
        "model": "Apeos 4620SZ",
        "category": "A4 Mono MFP",
        "product_type": "A4 Mono Multifunction Printer",
        "paper_size": "A4",
        "print_speed": "46 ppm",
        "print_resolution": CONTACT,
        "memory": "1 GB",
        "tray_capacity": "250-sheet Tray 1; 100-sheet bypass tray; 50-sheet SPDF",
        "connectivity": "Wi-Fi / mobile support",
        "warranty": "1 year",
        "description": "Fujifilm Apeos A4 mono multifunction option for office productivity and document handling.",
        "key_features": ["46 ppm speed", "Single-pass two-sided scanner feeder", "Two-sided print/copy", "Wi-Fi and mobile support"],
        "specifications": specs(Functions="Two-sided Print / Copy", SPDF="Single Pass 2 Sides Feeder, 50 sheets"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B7125",
        "category": "A3 Mono MFP",
        "product_type": "A3 Mono Multifunction Printer",
        "paper_size": "A3",
        "print_speed": "25 ppm",
        "print_resolution": CONTACT,
        "memory": "4 GB",
        "tray_capacity": "520-sheet Tray 1; optional 520-sheet Tray 2; 100-sheet bypass tray; 130-sheet SPDF",
        "connectivity": "Mobile printing available",
        "warranty": "1 year",
        "description": "A3 mono multifunction printer for larger-format black-and-white document workflows.",
        "key_features": ["Copy, print and scan", "25 ppm speed", "130-sheet single-pass automatic document feeder", "Mobile printing available"],
        "specifications": specs(Processor="1.05 GHz", SPDF="130 sheets", **{"Duty Cycle": "1,07,000 copies"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "B7135",
        "category": "A3 Mono MFP",
        "product_type": "A3 Mono Multifunction Printer",
        "paper_size": "A3",
        "print_speed": "35 ppm",
        "print_resolution": CONTACT,
        "memory": "4 GB",
        "tray_capacity": "520-sheet Tray 1; optional 520-sheet Tray 2; 100-sheet bypass tray; 130-sheet SPDF",
        "connectivity": "Mobile printing available",
        "warranty": "1 year",
        "description": "A3 mono MFP for offices, schools and departments with high document handling needs.",
        "key_features": ["Copy, print and scan", "35 ppm speed", "130-sheet single-pass automatic document feeder", "Mobile printing available"],
        "specifications": specs(Processor="1.05 GHz", SPDF="130 sheets", **{"Duty Cycle": "1,53,000 copies"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "C7120",
        "category": "A3 Colour MFP",
        "product_type": "A3 Colour Multifunction Printer",
        "paper_size": "A3",
        "print_speed": "25 ppm",
        "print_resolution": CONTACT,
        "memory": "4 GB",
        "tray_capacity": "520-sheet Tray 1; 520-sheet Tray 2; 100-sheet bypass tray",
        "connectivity": CONTACT,
        "warranty": "1 year",
        "description": "A3 colour multifunction printer option for professional colour office documents and scanning workflows.",
        "key_features": ["A3 colour multifunction printer", "25 ppm brochure-listed speed", "4 GB memory", "Two 520-sheet trays and 100-sheet bypass tray"],
        "specifications": specs(Processor="1.05 GHz", Functions="Copy / Print / Scan"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "C7130",
        "category": "A3 Colour MFP",
        "product_type": "A3 Colour Multifunction Printer",
        "paper_size": "A3",
        "print_speed": "35 ppm",
        "print_resolution": CONTACT,
        "memory": "4 GB",
        "tray_capacity": "520-sheet main tray; 100-sheet bypass tray",
        "connectivity": "Network, Wi-Fi printing",
        "warranty": "1 year",
        "description": "A3 colour MFP for colour output, larger paper handling and multifunction productivity.",
        "key_features": ["A3 colour multifunction printer", "35 ppm speed", "4 GB memory", "Network and Wi-Fi printing"],
        "specifications": specs(Processor="1.05 GHz", Functions="Copy / Print / Scan"),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Lexmark",
        "model": "CX951",
        "category": "A3 Colour MFP",
        "product_type": "Colour Multifunction Printer",
        "paper_size": "4 x 6 inches to 12 x 18 inches",
        "print_speed": "35 ppm",
        "print_resolution": CONTACT,
        "memory": "4 GB",
        "tray_capacity": "550-sheet standard paper capacity; 700-sheet bypass tray; 200-sheet SPDF",
        "connectivity": "WiFi, USB, Ethernet",
        "warranty": "1 year",
        "description": "Colour multifunction printer option included in the client product portfolio.",
        "key_features": ["35 ppm speed", "200-sheet single-pass automatic document feeder", "4 GB memory", "WiFi, USB and Ethernet connectivity"],
        "specifications": specs(SPDF="200 sheets", **{"Duty Cycle": "20,000 copies per month", "Paper Thickness": "300 gsm main and bypass trays"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
    {
        "brand": "Xerox / Fujifilm",
        "model": "C8235",
        "category": "A3 Colour MFP",
        "product_type": "A3 Colour Multifunction Printer",
        "paper_size": "12.6 x 19.2 inches",
        "print_speed": "35 ppm",
        "print_resolution": "1200 x 2400 dpi",
        "memory": CONTACT,
        "tray_capacity": CONTACT,
        "connectivity": CONTACT,
        "warranty": CONTACT,
        "description": "A3 colour multifunction printer option for office colour output and document workflows.",
        "key_features": ["35 ppm speed", "LED technology machine", "Colour copier, printer, scanner and duplex", "Easy-to-use touch screen"],
        "specifications": specs(Functions="Colour Copier / Printer / Scanner and Duplex", **{"Paper Weight": "300 gsm", "Power Saving": "More savings on power bill"}),
        "brochure": "xerox-fujifilm-printers-mfp.pdf",
    },
])


class Command(BaseCommand):
    help = "Seed brochure-backed brands, categories, and products."

    def handle(self, *args, **options):
        media_brochures = Path(settings.MEDIA_ROOT) / "brochures"
        media_brochures.mkdir(parents=True, exist_ok=True)

        seeded = 0
        for item in CATALOG:
            brand, _ = Brand.objects.update_or_create(
                name=item["brand"],
                defaults={
                    "slug": slugify(item["brand"]),
                    "description": f"{item['brand']} products supplied and supported by Surya Enterprises.",
                    "is_active": True,
                },
            )
            category, _ = Category.objects.update_or_create(
                slug=slugify(f"{brand.name} {item['category']}"),
                defaults={
                    "brand": brand,
                    "name": item["category"],
                    "description": f"{item['category']} options for office and institutional printing.",
                    "is_active": True,
                },
            )

            brochure_name = item["brochure"]
            source = FRONTEND_BROCHURES / brochure_name
            if source.exists():
                copyfile(source, media_brochures / brochure_name)

            slug = slugify(item["model"])
            Product.objects.update_or_create(
                slug=slug,
                defaults={
                    "brand": brand,
                    "category": category,
                    "name": f"{brand.name} {item['model']}",
                    "model": item["model"],
                    "product_type": item["product_type"],
                    "paper_size": item["paper_size"],
                    "print_speed": item["print_speed"],
                    "print_resolution": item["print_resolution"],
                    "memory": item["memory"],
                    "tray_capacity": item["tray_capacity"],
                    "connectivity": item["connectivity"],
                    "warranty": item["warranty"],
                    "description": item["description"],
                    "key_features": item["key_features"],
                    "specifications": item.get("specifications", {}),
                    "brochure_file": f"brochures/{brochure_name}",
                    "is_featured": item.get("is_featured", False),
                    "is_active": True,
                },
            )
            seeded += 1

        self.stdout.write(self.style.SUCCESS(f"Seeded {seeded} products."))
